version: '3.9'
services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
  sensors:
    image: water_station
    init: true
    devices:
    - /dev/gpiomem
    privileged: true
    links:
      - influxdb
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
volumes:
  influxdb:
    external: true
  grafana:
    external: true